### ISSUE TITLE
Question - Distance assessment XY vs XYZ

### ISSUE THREAD

**Issue by Ewan-O** [TimSC/pyshull#1]
Hi,

Not a huge issue, but more of a question really, that would help my workflow immensely. Firstly, really appreciate your posting this code, a pure-python only solution for triangulation is exactly what I need. 

I have noticed this code works well for surface triangulation where points are more likely to be based on / around one plane axis (xy) but doesn't work for instances where points cross between base axis like xy to xz.

The CalcDist function seems to assess x and y data only to gather nearest relationahipa. Is there a way to adjust the code so it assesses spatial relationships in xyz?

My CalcDist would be (to ensure positive values):

import cmath
from cmath import *

def CalcDist(a,b):
    x=(a[0] - b[0]) **2
    y=(a[1] - b[1]) **2
    z=(a[2] - b[2]) **2
    return cmath.sqrt(x+y+z).real

**Comment by TimSC** [comment]
If I understand it correctly, I think the S-hull algorithm is limited to 2D? Probably a different approach would be needed for 3D. http://www.s-hull.org/

**Comment by Ewan-O** [comment]
Thanks for the information. 
I may just have to write a solver/function to assess each of my planar point sets (as 2.5d) and stitch the results together.
